### ISSUE TITLE
Container runs in a loop when the restart policy is set

### ISSUE THREAD

**Issue by badermaiss** [vogler/free-games-claimer#113]
Hi! The container keeps running the scripts in a loop instead of shutting down when the restart policy is set to "unless-stopped".

**Comment by silentguy256** [comment]
Well, that is what you told it to do. This is currently not set to idle and try again later, it just runs once and then exits. Restart unless-stopped meant that if it exists it will restart unless it exists because you explicitly stopped it.
You want to either have no restart policy or the restart policy "no". That way it will just stop after it ran. Personally I currently have it in a cron job to run once a day
