### ISSUE TITLE
Unable to choose Twitch account

### ISSUE THREAD

**Issue by HandyHat01** [vogler/free-games-claimer#12]
Hey there, thanks for all your work on this!

I'm trying to claim prime gaming games, but am unable to scroll down and choose the Twitch account I'm claiming on as I have more than one linked to the Amazon account.

![image](https://user-images.githubusercontent.com/102835118/161350050-9a875bb6-1777-4ca7-9a0e-095451d85ca8.png)
 
The code waits for the element to become visible around 30 times and then eventually times out.

**Comment by vogler** [comment]
For now, you can increase the `height` here: https://github.com/vogler/free-games-claimer/blob/0381b73d5eabc0cec36afa142b6a99f64a443d08/prime-gaming.js#L17

You can only claim each game on one Twitch account and you usually select the same one?
What's the reason for having several linked?
Not sure if I have my Twitch still linked since they changed the client from Twitch to Amazon Gaming.
It's a bit hard to implement it remotely.
Maybe you can try the following:
- run `PWDEBUG=1 node epic-games`
- record the screen/windows with https://recordscreen.io/ (or similar, haven't tried it)
- step through the debugger until the account selection
- `cmd + shift + C` (`ctrl` on Win) to open DevTools and hover over thing to be clicked
- in the Elements tab we now just need to find some way to identify it (text, CSS, other attributes)

**Comment by vogler** [comment]
@HandyHat01 I'll close this. Feel free to reopen with more details.

**Comment by HandyHat01** [comment]
Hey @vogler, apologies for the delay in responding.

I ran `npx cross-env PWDEBUG=1 node prime-gaming show` and then recorded the window, stepping through the debugger until the account selection screen appeared. Changing the viewport size seemed to stop the code from working, so instead I zoomed out when the pop-up opened.

https://user-images.githubusercontent.com/102835118/179315735-6cff5038-6e92-44cd-a290-57cccb329630.mp4


> What's the reason for having several linked?

I linked multiple back when the client was the Twitch client in order to allow family members to claim games I already owned.

**Comment by HandyHat01** [comment]
> In your normal browser the popup appears vertically centered?

It does. The behaviour in the chromium window is odd.

> Does this pop up for each game or does it remember your selection for some time?

Once selected, my selection is remembered in the browser until cookies are cleared/I'm logged out. The default Twitch account has to be selected again per browser though. I think this means once the user has selected once it can be ignored, just like logins.

I tried adding that code after https://github.com/vogler/free-games-claimer/blob/4ff208a6b0047f4cfebbf77250383ebc31b01644/prime-gaming.js#L82

but it fails because the popup isn't in view. Even though the code claims to be scrolling into view, it doesn't.

**Comment by vogler** [comment]
I'll add an option to change the used browser profile, then you can keep a profile for each Twitch account (still have to select it initially though).

**Comment by vogler** [comment]
You can now use `BROWSER_DIR=data/browser2 node prime-gaming.js` to claim for several accounts.
