### ISSUE TITLE
epic games time out

### ISSUE THREAD

**Issue by RakibRyan** [vogler/free-games-claimer#244]
```
--- Exception:
page.fill: Timeout 180000ms exceeded.
=========================== logs ===========================
waiting for locator('#password')
============================================================
    at C:\Users\me\Downloads\free-games-claimer-main\epic-games.js:89:18 {
  name: 'TimeoutError'
}
```

**Comment by Errox** [comment]
Here too

**Comment by vogler** [comment]
Please update before opening an issue.
https://github.com/vogler/free-games-claimer/blob/739fb0dbfe19d065a68d39fc1b971e58b83d4b85/epic-games.js#L90
Yours is in line 89 instead of 90.
You're probably missing https://github.com/vogler/free-games-claimer/commit/a374d483451f1fa19c0f9f461e32cb37a4b46fd7.
