### ISSUE TITLE
"Unavailable" games make the script halt and quit

### ISSUE THREAD

**Issue by Kraker01** [vogler/free-games-claimer#35]
As per title, I'm in a region where a particular game (Epic Cheerleader Pack) isn't available so the script cannot redeem it and exit with a Timeout error. This is the error:

Current free game: Epic Cheerleader Pack
  Not in library yet! Click GET.
page.click: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-testid="purchase-cta-button"]"
  selector resolved to visible <button disabled class="css-1rcvlh3" aria-disabled="true…>…</button>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not enabled - waiting...
============================================================
    at file:///C:/Users/thekr/Downloads/Bottini/free-games-claimer-main/epic-games.js:137:18 {
  name: 'TimeoutError'

**Comment by vogler** [comment]
Is this no longer an issue or why did you close it?
The script is checking the available games for US, but only since it relies on English text:
https://github.com/vogler/free-games-claimer/blob/aa53075ab512835c1de79ea262f83923da7f69ef/epic-games.js#L13
https://github.com/vogler/free-games-claimer/blob/aa53075ab512835c1de79ea262f83923da7f69ef/epic-games.js#L106
Could check if there's a way to see the available games for your region but still have English language.
