### ISSUE TITLE
[gog] 'gog failed: Cannot read properties of null (reading '1')'

### ISSUE THREAD

**Issue by shinji257** [vogler/free-games-claimer#398]

**Comment by FluffyClaws** [comment]
Did you know that the more info on an issue is provided the more easily it is to locate and fix?

Nevertheless, I did encounter the same error, _**BUT, after running the script the second time after claiming the game.**_

Full error looks like following:
```
TypeError: Cannot read properties of null (reading '1')
    at file:///free-games-claimer/gog.js:102:62
```

So I would assume the issue is that on the consecutive runs the matching text is not found returning null, and attempting to access [1] on the null value.

```
const title = text.match(/Claim (.*) and don't miss the/)[1];
```

I`ve never encountered this before personally, and I run the script twice each time, so most likely the are some changes on the GoG website that have caused this. Not sure how to test without a giveaway though.

**Comment by vinnymac** [comment]
I can confirm this happens after there are no more games to claim, so likely a change on the site occurred. If a game is available to claim it works just fine.

**Comment by silkyclouds** [comment]
Can we eventually get a fix in the docker image based on @jordyamc comment ? I'm getting this error message as well and would like to get rid of it. 
'gog failed: Cannot read properties of null (reading '1')'

**Comment by NeoMod** [comment]
@jordyamc Thank you! 👍

**Comment by depau** [comment]
> I changed it to this to fix this error
> 
> ```diff
> - const title = text.match(/Claim (.*) and don't miss the/)[1];
> + const match_all = text.match(/Claim (.*) and don't miss the|Success! (.*) was added to/);
> + const title = match_all[1] ? match_all[1] : match_all[2];
> ```

@jordyamc 
Can you please submit a pull request?

**Comment by AgentTechnoman** [comment]
@depau
https://github.com/vogler/free-games-claimer/pull/411

**Comment by vogler** [comment]
Thanks, merged :)
