### ISSUE TITLE
Not scraping for GOG Games

### ISSUE THREAD

**Issue by ma7xrk** [vogler/free-games-claimer#52]
This script is outstanding! I have started using it today. I have been able to get everything working with Epic and Prime. I have not been prompted for creds for GOG, is this expected behaviour if there are no available games or is there an issue where it isn't prompting for GOG creds/scraping for GOG games?

**Comment by vogler** [comment]
Just didn't have it run by default so far. It's included now. See #51 regarding update.

**Comment by ma7xrk** [comment]
Thank you for confirming. I am also wondering if you are able to clarify how options can be amended. I am sure it is just my lack of programming/docker experience. I am looking to update the notification settings but I am not sure if I should be amending this on a external terminal (I am using PowerShell) or if I should be doing it within docker (not sure where I should be doing this). I am also unsure how to amend using dotenv. I am sorry for my lack of understanding.

**Comment by vogler** [comment]
Yea, I can see how it can be confusing since there are several ways mentioned.

> On Linux/macOS you can also prefix the variables you want to set, for example `EMAIL=foo@bar.baz SHOW=1 node epic-games` will show the browser and skip asking you for your login email.

This is how to do it if you are running it without docker or if you change the command to be run inside docker.

> For Docker you can pass variables using `-e VAR=VAL`, for example `docker run -e EMAIL=foo@bar.baz ...` or using `--env-file` (see [docs](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file)). If you are using [docker compose](https://docs.docker.com/compose/environment-variables/), you can put them in the `environment:` section.

Since you run it in docker, this is the way to go. So you can just add `-e NOTIFY='...'` to the `docker run` command you execute in PowerShell.
If that works, you can also put the options in a local file and load it with the mentioned `--env-file`.

> You can put options in `data/config.env` which will be loaded by [dotenv](https://github.com/motdotla/dotenv).

dotenv can also load options, which is relevant when you run it without docker, or if you want to store the options inside the `fgc` volume (instead of somewhere on the host file system), together with the other data.
If you use Docker Desktop, you can see the files in the volume (but sadly not edit them):
![image](https://user-images.githubusercontent.com/493741/217476695-1bcd08ac-cf47-4edf-8ffb-2186bbd929a3.png)
