### ISSUE TITLE
Screenshot issues with Prime Gaming

### ISSUE THREAD

**Issue by kennymc-c** [vogler/free-games-claimer#82]
Every time the Prime Gaming script runs, a screenshot is taken, even if no new games are available. Since this is not the case with Epic and GOG, I assume this is a bug. Also, the screenshot does not show all games and cuts off at the top and has a lot of space at the bottom.
The screenshots of the redeemed games in the internal folder show it before it was claimed.  Is this on purpose or also not intended?

**Comment by vogler** [comment]
> even if no new games are available. Since this is not the case with Epic and GOG, I assume this is a bug.

Yes, fixed.

> the screenshot does not show all games and cuts off at the top and has a lot of space at the bottom.

Ghetto-fixed by increasing viewport height to 3000px and scrolling to the bottom to fade in all games.

> The screenshots of the redeemed games in the internal folder show it before it was claimed. Is this on purpose or also not intended?

Was intended to have the remaining time to claim there, but now it seems it's also there after it was claimed. Moved the screenshot down after the click to claim, but does not wait, so most of the time there's still the loading button, but I guess that's not really important enough to wait for.
