### ISSUE TITLE
apprise fails if spaces in `NOTIFY_TITLE`: `ERROR - Unsupported URL: http://free`

### ISSUE THREAD

**Issue by DevXen** [vogler/free-games-claimer#97]
When i run the docker container on unraid i get these messages, both for epic and for prime. the games were still claimed so i assume it's not anything serious. 

2023-03-16 21:24:32.743 started checking prime-gaming
Signed in as Dev
Number of already claimed games (total): 14
Number of free unclaimed games (Prime Gaming): 1
Current free game: Faraway: Arctic Escape
Number of free unclaimed games (external stores): 0
stdout: 2023-03-16 15:24:50,641 - ERROR - Unsupported URL: http://free
2023-03-16 15:24:50,641 - ERROR - Unsupported URL: http://Games
2023-03-16 15:24:50,641 - ERROR - Unsupported URL: http://added

**Comment by vogler** [comment]
The output does not make any sense to me since the text 'free Games added' does not even appear anywhere and there should be no URLs printed to the console in your example. What non-default options are you using? Maybe it has to do with notifications.

Since the time format (, instead of . after seconds) and time zone (15 instead of 21) are different, it is likely some software you have running that is processing the terminal output (maybe to make URLs clickable).

**Comment by DevXen** [comment]
So for the notifications I have:

mailto://Username:AppPassWord@gmail.com

But I did just noticed I have this in the nitofy title.

New free Games added

So maybe that's it?

**Comment by vogler** [comment]
Thanks! Fixed. Forgot to put the title in quotes, so apprise complained if there were spaces in it.
